# TODO - name of service, image name, need 2 of these I guess?
# Args to do diff or full dump
version: "3.9"
services:
  factorio_dump_data:
    image: dedlyspyder/factorio-data-analysis:latest
    container_name: factorio-data-analysis_dump_data
    command: final
    volumes:
      - ${MODS_DIRECTORY:-../../mods}:/factorio/mods
      - ${OUTPUT_DIRECTORY:-../../data}:/output
