name: Build Docker
run-name: Docker Build for ${{ inputs.headless_docker_version }}
on:
  workflow_dispatch:
    inputs:
      headless_docker_version:
        description: 'Version of the factorio-headless-ubuntu docker image to build against'
        required: true
        type: string
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: factorioVersion
        name: Parse Factorio version from Headless Docker Version
        run: echo "version=$(echo "${{ inputs.headless_docker_version }}" | cut -d "-" -f 1)" >> $GITHUB_OUTPUT
      - id: scriptVersion
        name: Parse Factorio version from Headless Docker Version
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - id: validateTag
        name: Check if this build has already been completed
        run: ./.github/workflows/scripts/validate_new_version.sh "${{ steps.versionParse.outputs.version }}-${{ steps.scriptVersion.outputs.version }}" # Outputs `exists` as true/false
      - name: Build and push image
        if: steps.validateTag.outputs.exists == 'false'
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          build-args: HEADLESS_VERSION=${{ inputs.headless_docker_version }}
          push: true
          tags: |
            dedlyspyder/factorio-data-analysis:${{ steps.factorioVersion.outputs.version }}-${{ steps.scriptVersion.outputs.version }}
            dedlyspyder/factorio-data-analysis:latest
